version: "3"

services:
  url-shortener-web:
    image: cranki/url-shortener-web:dev
    container_name: url-shortener-web
    ports:
      - 3000:80
    depends_on:
      - url-shortener-worker
    networks:
      - cranki
  url-shortener-worker:
    image: cranki/url-shortener:dev
    container_name: url-shortener-worker
    ports:
      - 8888:8888
    depends_on:
      - url-shortener-db
    networks:
      - cranki
  url-shortener-db:
    image: cranki/url-shortener-mysql:1.0
    container_name: url-shortener-db
    networks:
      - cranki

networks:
  cranki:
    driver: "bridge"
